services:
  focalboard:
    container_name: focalboard
    image: mattermost/focalboard
    hostname: docker-focalboard
    ports:
      - 8080:8000/tcp
    volumes:
      - focalboard:/opt/focalboard/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - lan
    restart: always

volumes:
  focalboard: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
