services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    hostname: docker-heimdall
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - heimdall:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - lan
    restart: always

volumes:
  heimdall: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
