services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    hostname: docker-vaultwarden
    ports:
      - 80:80/tcp
    environment:
      ADMIN_TOKEN_FILE: /run/secrets/VAULTWARDEN_PASSWORD
      SIGNUPS_ALLOWED: true
    secrets:
      - VAULTWARDEN_PASSWORD
    volumes:
      - vaultwarden:/data
    networks:
      - lan
    restart: always

secrets:
  VAULTWARDEN_PASSWORD:
    file: ./secrets/VAULTWARDEN_PASSWORD

volumes:
  vaultwarden: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
