services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    hostname: docker-prometheus
    ports:
      - 9090:9090/tcp
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    #environment:
    volumes:
      - prometheus:/etc/prometheus/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - lan
    restart: always

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    hostname: docker-node-exporter
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    networks:
      - lan
    restart: always

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    hostname: docker-cadvisor
    ports:
      - 8080:8080/tcp
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379/tcp

volumes:
  prometheus: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
