services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    hostname: docker-homepage
    ports:
      - 3000:3000/tcp
    volumes:
      - homepage:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # docker integrations
    networks:
      - lan
    restart: always

volumes:
  homepage: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
