services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    hostname: docker-jenkins
    ports:
      - 8080:8080/tcp
      - 50000:50000/tcp
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - lan
    restart: always

volumes:
  jenkins: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
