services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    hostname: docker-jellyfin
    ports:
      - 8096:8096/tcp
    environment:
      JELLYFIN_PublishedServerUrl: https://your.domain
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/smb-mount:/media
    networks:
      - lan
    restart: always

volumes:
  jellyfin_config: {}
  jellyfin_cache: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
