services:
  minecraft-srv1:
    container_name: mc-srv1
    image: itzg/minecraft-server
    hostname: mc-srv1
    ports:
      - 58880:25565/tcp
    environment:
      # General options
      INIT_MEMORY: 2G
      MAX_MEMORY: 8G
      ENABLE_ROLLING_LOGS: true

      # Server
      TYPE: FORGE
      EULA: true
      VERSION: 1.21.4
      SERVER_NAME: mc-srv1.yourdomain.ru
      MOTD: |
        §l§6First line§r
        §eSecond line§r
      MODS: "/data/mods"
      DIFFICULTY: normal
      ICON: /data/mc-srv1-ico.png
      #OVERRIDE_ICON: true
      MAX_PLAYERS: 10
      ALLOW_NETHER: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ENABLE_COMMAND_BLOCK: false
      GENERATE_STRUCTURES: true
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS: true
      SPAWN_NPCS: true
      # SEED: ""
      MODE: survival
      LEVEL: "saveWorld"
      ONLINE_MODE: false

      # RCON
      #RCON_CMDS_STARTUP: |-

      #RCON_CMDS_ON_CONNECT: |-

      #RCON_CMDS_FIRST_CONNECT: |-

      #RCON_CMDS_LAST_DISCONNECT: |-

    volumes:
      - mc-1.21.4:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mc-srv
    restart: always

  minecraft-srv2:
    container_name: mc-srv2
    image: itzg/minecraft-server
    hostname: mc-srv2
    ports:
      - 58890:25565/tcp
    environment:
      # General options
      INIT_MEMORY: 2G
      MAX_MEMORY: 8G
      ENABLE_ROLLING_LOGS: true

      # Server
      TYPE: FORGE
      EULA: true
      VERSION: 1.18.2
      SERVER_NAME: mc-srv2.yourdomain.ru
      MOTD: |
        §l§6First line§r
        §eSecond line§r
      MODS: "/data/mods"
      DIFFICULTY: normal
      ICON: /data/mc-srv2-ico.png
      #OVERRIDE_ICON: true
      MAX_PLAYERS: 10
      ALLOW_NETHER: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ENABLE_COMMAND_BLOCK: false
      GENERATE_STRUCTURES: true
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS: true
      SPAWN_NPCS: true
      # SEED: ""
      MODE: survival
      LEVEL: "saveWorld"
      ONLINE_MODE: false

      # RCON
      #RCON_CMDS_STARTUP: |-

      #RCON_CMDS_ON_CONNECT: |-

      #RCON_CMDS_FIRST_CONNECT: |-

      #RCON_CMDS_LAST_DISCONNECT: |-
    volumes:
      - mc-1.18.2:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mc-srv
    restart: always

volumes:
  mc-1.21.4: {}
  mc-1.18.2: {}

networks:
  mc-srv:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
