services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    hostname: docker-nginx-proxy-manager
    ports:
      - 80:80/tcp
      - 81:81/tcp
      - 443:443/tcp
    volumes:
      - nginx:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - lan
    restart: always

volumes:
  nginx: {}
  letsencrypt: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
