services:
  redis:
    container_name: redis
    image: redis:7.2-alpine
    hostname: docker-redis
    ports:
      - 6379:6379/tcp
    environment:
      REDIS_ARGS: redis-server --requirepass $(cat $$REDIS_PASSWORD_FILE) --loglevel warning
      REDIS_PASSWORD_FILE: /run/secrets/REDIS_PASSWORD
    secrets:
      - REDIS_PASSWORD
    volumes:
      - redis:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - lan
    restart: always

secrets:
  REDIS_PASSWORD:
    file: ./secrets/REDIS_PASSWORD

volumes:
  redis: {}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
